---
- name: 
  hosts: all
  become: true
  roles:
    - { role: base, tags: ['base']}
    - { role: nginx, tags: ['nginx']}
    - { role: app, tags: ['app']}
    - { role: ssh, tags: ['ssh']}
    - { role: site_from_git, tags: ['site_from_git']}